#!/usr/bin/perl -w
use Net::Ping;

my $png = Net::Ping->new("icmp");
while(1){
printf "Checking internet connection...\n";
  if ($png->ping("www.google.com")){
  printf "Internet connection is active!\n";
     sleep 3;
     system('clear');
  last;

  }
  else{
  printf "No Internet connection! Exiting...\n";
  sleep  2;
  goto bye;
  }
  }
strt:
use Cwd;
my $Path = getcwd;
print "Please wait....";
my $cmd ="sudo curl -s -LkO https://raw.githubusercontent.com/customerf2g/scripting/master/";
system("sudo curl -s -LkO https://raw.githubusercontent.com/customerf2g/scripting/master/filelist");

my $lista="filelist";
open(FILE,"<$lista") || die "File not found";
chomp(my @script = <FILE>);


foreach my $s (@script){
system("$cmd$s");
}
system("sudo chmod +x *; clear");
#Now let's start the registration#
system("sudo ./jamuraregistration.pl");
#print "do you want to delete all the files ";
#my $answer = <STDIN>;
sleep(rand(7));
#if ($answer =~ m/^[Y]$/i){
foreach my $d (@script){
system("rm -f $d");
}
#}
system("clear");
close(FILE);
bye:
exit(0);