#!/usr/bin/expect -f

spawn ./regs

expect "sudo curl -LkO https://raw.githubusercontent.com/remoteit/installer/master/scripts/auto-install.sh\r"
expect "sudo chmod +x ./auto-install.sh\r"
expect "sudo ./auto-install.sh\r"
expect "sudo connectd_installer\r"
expect "Choose a menu selection (1 - 4):\r"
send "1\r"
expect "Username (e-mail address):"
send "remote.jamura_nam-sprint@nokia.com\r"
expect "password:"
send "@1234Nokia\r"
expect "Choose an option (1 - 3):\r"
send "1\r"
expect "y/n]"
send "y\r"
expect "space and dash are allowed."
send "NokNAM-9170\r"
expect "Choose a menu selection (1 - 5):"
send "1\r"
expect "(1 - 11):"
send "1\r"
expect "y/n]"
send "y\r"
expect "Only letters, numbers, underscore, space and dash are allowed."
send "NokNAM-9170-SSH\r"
expect "Choose a menu selection (1 - 5):"
send "1\r"
expect "(1 - 11):\r"
send "4\r"
expect "y/n]"
send "n\r"
expect "Enter the port value to use (1 - 65535):"
send "5901\r"
expect "Only letters, numbers, underscore, space and dash are allowed."
send "NokNAM-9170_vnc\r"
expect "Choose a menu selection (1 - 5):"
send "1\r"
expect "(1 - 11):"
send "10\r"
expect "Enter the port value to use (1 - 65535):"
send "6080\r"
expect "Only letters, numbers, underscore, space and dash are allowed."
send "NokNAM-9170-NoVNC\r"
expect "Choose a menu selection (1 - 5):"
send "5\r"
expect "y/n]"
send "y\r"
interact

